baseURL = "http://acupofair.github.io"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 20
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "bw"
relativeURLs = true
theme = "hugo-coder"
title = "Cup Air"

disqusShortname = "yourdiscussshortname"

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = 'dracula'
# style = 'fruity'
# style = 'native'
# style = 'vim'
# style = 'solarized-dark256'
tabWidth = 4
[markup.tableOfContents]

endLevel = 4
ordered = false
startLevel = 1
[params]
author = "Cup Air"
avatarURL = "images/white_leaf.PNG"
description = "Cup Air's site"
info = "I'll Be a Splendid Passer-by"
keywords = "blog,developer,personal"
#gravatar = "john.doe@example.com"   

dateFormat = "January 2, 2006"
footerContent = "Boom!!!"
hideCopyright = false
hideCredits = false
hideFooter = false
since = 2019
# Git Commit in Footer, uncomment the line below to enable it.

enableGitInfo = true
enableGitalk = true

rtl = false
# Specify light/dark colorscheme     
# Supported values:                  
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)

colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider

hideColorSchemeToggle = false
# Series see also post count         

maxSeeAlsoItems = 5
# Enable Twemoji                     

enableTwemoji = true
# Custom CSS                         

customCSS = []
# Custom SCSS                        

customSCSS = []
# Custom JS                          

customJS = []
# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]                 
#     siteID = "ABCDE"                     
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"  

# # If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]              
#     domain = "example.com"               
#     # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"  

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
# [params.goatCounter]                     
#     code = "code"                        

googleAnalytics = 'G-PXZZ7M9MGE'
[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[params.gitalk]
admin = "ACupofAir" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
clientID = "86b4d4ae4b906754b70d" # Your client ID
clientSecret = "3aed59c23bb112d689173dd8bb449dddcf33571d" # Your client secret
owner = "ACupofAir" # Your GitHub ID
repo = "acupofair.github.io" # The repo to store comments
# id= "location.pathname" # The unique id of the page.

createIssueManually = false # If it is 'false', it is auto to make a Github issue when the administrators login.
distractionFreeMode = true # Enable hot key (cmd|ctrl + enter) submit comment.
labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
perPage = 15 # Pagination size, with maximum 100.
[[params.social]]
icon = "fa fa-github fa-2x"
name = "Github"
url = "https://github.com/ACupofAir/"
weight = 6
# [[params.social]]                        
#    name = "Gitlab"                       
#    icon = "fa fa-gitlab"                 
#    weight = 2                            
#    url = "https://gitlab.com/johndoe/"          
[[params.social]]
icon = "fa fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/AirCupT/"
weight = 6
# [[params.social]]                               
#     name = "LinkedIn"                           
#     icon = "fa fa-linkedin"                     
#     weight = 4                                  
#     url = "https://www.linkedin.com/in/johndoe/"
[[params.social]]
icon = "fa fa-medium fa-2x"
name = "Medium"
url = "https://medium.com/@thoughts.times"
weight = 6
[[params.social]]

icon = "fa fa-rss fa-2x"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://acupofair.github.io/index.xml"
weight = 6
[languages]
[languages.en]

languageName = "English"
[languages.en.menu]

[[languages.en.menu.main]]
name = "Blogs"
url = "posts/"
weight = 2

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 2

[[languages.en.menu.main]]
name = "Categories"
url = "categories/"
weight = 2

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [":fileModTime", ":default"]
publishDate = ['publishDate', 'date']
